### ISSUE TITLE
Crash if image 1x1

### ISSUE THREAD

**Issue by AuracleTech** [Jose134/HDtoSD#1]
Thank you a lot for your program by the way
Can you just add a check if the image is 1x1 just make the SD version also 1x1
Cause it's trying to divide 1 pixel by two
Thank you :) !

**Comment by Jose134** [comment]
Sorry for the late answer (never saw the notification lol).
As far as I remember I already fixed this long ago (check Program.cs line 180)

`if (srcImage.Width * scale >= 1 && srcImage.Height * scale >= 1) {`

This if runs before resizing the image. If the final result doesn't have a valid resolution then it just copies or moves the file. Did the program crash when you ran it? If so, can you provide some more information?

**Comment by AuracleTech** [comment]
Well I used the up to date version bug still exists, it's taking another variable or something, I am too lazy to check others code

**Comment by Jose134** [comment]
Fixed, seems like my 2 years ago self didn't like to close files before trying to move them...
